version: '3.9'

services:
  database:
    image: mysql
    container_name: medicals_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'gcb'
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
